CREATE TABLE [dbo].[AG_ANO_ESCOLARIDADE_ESTADO_CARGO](
	[Ano] [int] NOT NULL,
	[CandidatoEscolaridadeID] [int] NOT NULL,
	[LocalidadeID] [int] NOT NULL,
	[CargoPoliticoID] [int] NOT NULL,
	[VlrTotalDeclarado] [numeric](16, 2) NOT NULL,
	[QtdTotalDeclarado] [int] NOT NULL,
 CONSTRAINT [PK_AG_ANO_ESCOLARIDADE_ESTADO_CARGO] PRIMARY KEY CLUSTERED 
(
	[Ano] ASC,
	[CandidatoEscolaridadeID] ASC,
	[LocalidadeID] ASC,
	[CargoPoliticoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[AG_ANO_ESCOLARIDADE_ESTADO_CARGO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_ESCOLARIDADE_ESTADO_CARGO_TDCargoPolitico] FOREIGN KEY([CargoPoliticoID])
REFERENCES [dbo].[TDCargoPolitico] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_ESCOLARIDADE_ESTADO_CARGO] CHECK CONSTRAINT [FK_AG_ANO_ESCOLARIDADE_ESTADO_CARGO_TDCargoPolitico]
GO

ALTER TABLE [dbo].[AG_ANO_ESCOLARIDADE_ESTADO_CARGO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_ESCOLARIDADE_ESTADO_CARGO_TDLocalidade] FOREIGN KEY([LocalidadeID])
REFERENCES [dbo].[TDLocalidade] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_ESCOLARIDADE_ESTADO_CARGO] CHECK CONSTRAINT [FK_AG_ANO_ESCOLARIDADE_ESTADO_CARGO_TDLocalidade]
GO

ALTER TABLE [dbo].[AG_ANO_ESCOLARIDADE_ESTADO_CARGO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_ESCOLARIDADE_ESTADO_CARGO_TPCandidatoEscolaridade] FOREIGN KEY([CandidatoEscolaridadeID])
REFERENCES [dbo].[TPCandidatoEscolaridade] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_ESCOLARIDADE_ESTADO_CARGO] CHECK CONSTRAINT [FK_AG_ANO_ESCOLARIDADE_ESTADO_CARGO_TPCandidatoEscolaridade]
GO

