CREATE TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO](
	[Ano] [int] NOT NULL,
	[CandidatoEscolaridadeID] [int] NOT NULL,
	[PartidoColigacaoID] [int] NOT NULL,
	[LocalidadeID] [int] NOT NULL,
	QtdCandidatos [int] NOT NULL, 
	[VlrTotalDeclarado] [numeric](16, 2) NOT NULL,
	[QtdTotalDeclarado] [int] NOT NULL,
 CONSTRAINT [PK_AG_ANO_SEXO_PARTIDO_ESTADO] PRIMARY KEY CLUSTERED 
(
	[Ano] ASC,
	[CandidatoEscolaridadeID] ASC,
	[PartidoColigacaoID] ASC,
	[LocalidadeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_TDLocalidade] FOREIGN KEY([LocalidadeID])
REFERENCES [dbo].[TDLocalidade] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO] CHECK CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_TDLocalidade]
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_TDPartidoColigacao] FOREIGN KEY([PartidoColigacaoID])
REFERENCES [dbo].[TDPartidoColigacao] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO] CHECK CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_TDPartidoColigacao]
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_TPCandidatoEscolaridade] FOREIGN KEY([CandidatoEscolaridadeID])
REFERENCES [dbo].[TPCandidatoEscolaridade] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO] CHECK CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_TPCandidatoEscolaridade]
GO

