CREATE TABLE [dbo].[AG_ANO_SEXO_PARTIDO_LOCAL_PIVOT](
	[Ano] [int] NOT NULL,
	[PartidoColigacaoID] [int] NOT NULL,
	[LocalidadeID] [int] NOT NULL,
	QtdMasculino [int] NOT NULL,
	QtdFeminino [int] NOT NULL,
	QtdTotal [int] NOT NULL
 CONSTRAINT [PK_AG_ANO_SEXO_PARTIDO_LOCAL_PIVOT] PRIMARY KEY CLUSTERED 
(
	[Ano] ASC,
	[PartidoColigacaoID] ASC,
	[LocalidadeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

