DELETE FROM [Estado];
GO
DBCC CHECKIDENT ('[Estado]', RESEED, 0);
GO
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Rondônia', 'RO', 'Norte')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Acre', 'AC', 'Norte')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Amazonas', 'AM', 'Norte')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Roraima', 'RR', 'Norte')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Pará', 'PA', 'Norte')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Amapá', 'AP', 'Norte')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Tocantins', 'TO', 'Norte')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Maranhão', 'MA', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ('Piauí', 'PI', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Ceará', 'CE', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Rio Grande do Norte', 'RN', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Paraíba', 'PB', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Pernambuco', 'PE', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Alagoas', 'AL', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Sergipe', 'SE', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Bahia', 'BA', 'Nordeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Minas Gerais', 'MG', 'Sudeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Espírito Santo', 'ES', 'Sudeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Rio de Janeiro', 'RJ', 'Sudeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'São Paulo', 'SP', 'Sudeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Paraná', 'PR', 'Sul')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Santa Catarina', 'SC', 'Sul')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Rio Grande do Sul', 'RS', 'Sul')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Mato Grosso do Sul', 'MS', 'Centro-Oeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Mato Grosso', 'MT', 'Centro-Oeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Goiás', 'GO', 'Centro-Oeste')
INSERT INTO [dbo].[Estado] ([Nome], [Sigla], [Regiao]) VALUES ( 'Distrito Federal', 'DF', 'Centro-Oeste')