DELETE FROM TDLocalidade;
GO

DBCC CHECKIDENT ('[TDLocalidade]', RESEED, 0);
GO

INSERT INTO TDLocalidade
SELECT DISTINCT NOME_UE, SIGLA_UF, ISNULL(ESTADO.REGIAO, 'BRASIL')
 FROM ImportacaoVaga
 LEFT JOIN Estado 
   ON ESTADO.Sigla = ImportacaoVaga.SIGLA_UF
ORDER BY NOME_UE