/*
	DELETE FROM ImportacaoBensCandidato
	DELETE FROM ImportacaoCandidato
	DELETE FROM ImportacaoArquivo
	

	--DROP TABLE ImportacaoBensCandidato
	--DROP TABLE ImportacaoCandidato
	--DROP TABLE ImportacaoArquivo
	--DROP TABLE ImportacaoTipoArquivo
*/ 
 

 
CREATE TABLE ImportacaoTipoArquivo
 (
	ID									INT				NOT NULL PRIMARY KEY,
	Nome								VARCHAR(30)		NOT NULL
 )
 
GO

INSERT INTO ImportacaoTipoArquivo VALUES (1, 'Candidatos')
 INSERT INTO ImportacaoTipoArquivo VALUES (2, 'Bens Dos Candidatos')
 INSERT INTO ImportacaoTipoArquivo VALUES (3, 'Legendas')
 INSERT INTO ImportacaoTipoArquivo VALUES (4, 'Vagas')
 
GO

CREATE TABLE ImportacaoArquivo
 (
	ID									INT IDENTITY	NOT NULL PRIMARY KEY,
	NomeArquivo							VARCHAR(200)	NOT NULL,
	TipoArquivoID						INT				NOT NULL FOREIGN KEY (TipoArquivoID) REFERENCES ImportacaoTipoArquivo(ID),
	Ano									INT				NOT NULL,
	UF									VARCHAR(02)		NOT NULL
 )
GO
 
CREATE TABLE ImportacaoCandidato
 (
	ID									INT IDENTITY PRIMARY KEY NOT NULL,
	ImportacaoArquivoID				    INT NOT NULL FOREIGN KEY (ImportacaoArquivoID) REFERENCES ImportacaoArquivo(ID),
	DATA_GERACAO						VARCHAR(MAX) NULL,
    HORA_GERACAO						VARCHAR(MAX) NULL,
    ANO_ELEICAO 						VARCHAR(MAX) NULL,
    NUM_TURNO 							VARCHAR(MAX) NULL,
    DESCRICAO_ELEICAO 					VARCHAR(MAX) NULL,
    SIGLA_UF 							VARCHAR(MAX) NULL,
    SIGLA_UE 							VARCHAR(MAX) NULL,
    DESCRICAO_UE 						VARCHAR(MAX) NULL,
    CODIGO_CARGO 						VARCHAR(MAX) NULL,
    DESCRICAO_CARGO 					VARCHAR(MAX) NULL,
    NOME_CANDIDATO 						VARCHAR(MAX) NULL,
    SEQUENCIAL_CANDIDATO 				VARCHAR(MAX) NULL,
    NUMERO_CANDIDATO 					VARCHAR(MAX) NULL,
    CPF_CANDIDATO 						VARCHAR(MAX) NULL,
    NOME_URNA_CANDIDATO 				VARCHAR(MAX) NULL,
    COD_SITUACAO_CANDIDATURA 			VARCHAR(MAX) NULL,
    DES_SITUACAO_CANDIDATURA 			VARCHAR(MAX) NULL,
    NUMERO_PARTIDO 						VARCHAR(MAX) NULL,
    SIGLA_PARTIDO 						VARCHAR(MAX) NULL,
    NOME_PARTIDO 						VARCHAR(MAX) NULL,
    CODIGO_LEGENDA 						VARCHAR(MAX) NULL,
    SIGLA_LEGENDA 						VARCHAR(MAX) NULL,
    COMPOSICAO_LEGENDA 					VARCHAR(MAX) NULL,
    NOME_LEGENDA 						VARCHAR(MAX) NULL,
    CODIGO_OCUPACAO 					VARCHAR(MAX) NULL,
    DESCRICAO_OCUPACAO 					VARCHAR(MAX) NULL,
    DATA_NASCIMENTO 					VARCHAR(MAX) NULL,
    NUM_TITULO_ELEITORAL_CANDIDATO 		VARCHAR(MAX) NULL,
    IDADE_DATA_ELEICAO 					VARCHAR(MAX) NULL,
    CODIGO_SEXO 						VARCHAR(MAX) NULL,
    DESCRICAO_SEXO 						VARCHAR(MAX) NULL,
    COD_GRAU_INSTRUCAO 					VARCHAR(MAX) NULL,
    DESCRICAO_GRAU_INSTRUCAO 			VARCHAR(MAX) NULL,
    CODIGO_ESTADO_CIVIL 				VARCHAR(MAX) NULL,
    DESCRICAO_ESTADO_CIVIL 				VARCHAR(MAX) NULL,
    CODIGO_COR_RACA 					VARCHAR(MAX) NULL,
    DESCRICAO_COR_RACA 					VARCHAR(MAX) NULL,
    CODIGO_NACIONALIDADE 				VARCHAR(MAX) NULL,
    DESCRICAO_NACIONALIDADE 			VARCHAR(MAX) NULL,
    SIGLA_UF_NASCIMENTO 				VARCHAR(MAX) NULL,
    CODIGO_MUNICIPIO_NASCIMENTO 		VARCHAR(MAX) NULL,
    NOME_MUNICIPIO_NASCIMENTO 			VARCHAR(MAX) NULL,
    DESPESA_MAX_CAMPANHA 				VARCHAR(MAX) NULL,
    COD_SIT_TOT_TURNO 					VARCHAR(MAX) NULL,
    DESC_SIT_TOT_TURNO 					VARCHAR(MAX) NULL,
    NM_EMAIL 							VARCHAR(MAX) NULL
)
GO


CREATE TABLE ImportacaoBensCandidato
(
	ID									INT IDENTITY PRIMARY KEY NOT NULL,
	ImportacaoArquivoID				    INT NOT NULL FOREIGN KEY (ImportacaoArquivoID) REFERENCES ImportacaoArquivo(ID),
	DATA_GERACAO						VARCHAR(MAX) NULL,
    HORA_GERACAO						VARCHAR(MAX) NULL,
    ANO_ELEICAO 						VARCHAR(MAX) NULL,
    DESCRICAO_ELEICAO					VARCHAR(MAX) NULL,
    SIGLA_UF 							VARCHAR(MAX) NULL,
    SQ_CANDIDATO 						VARCHAR(MAX) NULL,
    CD_TIPO_BEM_CANDIDATO 				VARCHAR(MAX) NULL,
    DS_TIPO_BEM_CANDIDATO 				VARCHAR(MAX) NULL,
    DETALHE_BEM 						VARCHAR(MAX) NULL,
    VALOR_BEM 							VARCHAR(MAX) NULL,
    DATA_ULTIMA_ATUALIZACAO 			VARCHAR(MAX) NULL,
    HORA_ULTIMA_ATUALIZACAO				VARCHAR(MAX) NULL
)
GO