CREATE TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO](
	[Ano] [int] NOT NULL,
	[CandidatoEscolaridadeID] [int] NOT NULL,
	[PartidoColigacaoID] [int] NOT NULL,
	[LocalidadeID] [int] NOT NULL,
	[OcupacaoID] [int] NOT NULL,
	[CargoPoliticoID] [int] NOT NULL,
	[VlrTotalDeclarado] [numeric](16, 2) NOT NULL,
	[QtdTotalDeclarado] [numeric](16, 2) NOT NULL,
 CONSTRAINT [PK_AG_ESTADO_SEXO_PARTIDO] PRIMARY KEY CLUSTERED 
(
	[Ano] ASC,
	[CandidatoEscolaridadeID] ASC,
	[PartidoColigacaoID] ASC,
	[LocalidadeID] ASC,
	[OcupacaoID] ASC,
	[CargoPoliticoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TDCargoPolitico] FOREIGN KEY([CargoPoliticoID])
REFERENCES [dbo].[TDCargoPolitico] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO] CHECK CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TDCargoPolitico]
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TDLocalidade] FOREIGN KEY([LocalidadeID])
REFERENCES [dbo].[TDLocalidade] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO] CHECK CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TDLocalidade]
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TDOcupacao] FOREIGN KEY([OcupacaoID])
REFERENCES [dbo].[TDOcupacao] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO] CHECK CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TDOcupacao]
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TDPartidoColigacao] FOREIGN KEY([PartidoColigacaoID])
REFERENCES [dbo].[TDPartidoColigacao] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO] CHECK CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TDPartidoColigacao]
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO]  WITH CHECK ADD  CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TPCandidatoEscolaridade1] FOREIGN KEY([CandidatoEscolaridadeID])
REFERENCES [dbo].[TPCandidatoEscolaridade] ([ID])
GO

ALTER TABLE [dbo].[AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO] CHECK CONSTRAINT [FK_AG_ANO_SEXO_PARTIDO_ESTADO_OCUPACAO_CARGO_TPCandidatoEscolaridade1]
GO

