SELECT TOP 1000  
		Bens.ANO_ELEICAO, Candidato.NOME_CANDIDATO, Candidato.DESCRICAO_ELEICAO, DS_TIPO_BEM_CANDIDATO, DETALHE_BEM, VALOR_BEM, *

  FROM ImportacaoCandidato					AS Candidato  	WITH(NOLOCK)
  JOIN [dbo].[ImportacaoBensCandidato]		AS Bens  		WITH(NOLOCK)
    ON Candidato.SEQUENCIAL_CANDIDATO = Bens.SQ_CANDIDATO
   AND Candidato.ANO_ELEICAO = Bens.ANO_ELEICAO
 WHERE Candidato.SIGLA_UF = 'SP'
   AND Candidato.DESCRICAO_UE = 'VOTORANTIM'
   AND (	 
			 Candidato.NOME_CANDIDATO = 'FERNANDO DE OLIVEIRA SOUZA'
		  OR Candidato.NOME_CANDIDATO = 'JAIR CASSOLA'
		  OR Candidato.NOME_CANDIDATO LIKE 'ERINALDO ALVES DA SILVA'
		  OR Candidato.NOME_CANDIDATO LIKE 'CARLOS ALBERTO LEITE'
		  OR Candidato.NOME_CANDIDATO LIKE 'RODRIGO PINTO CHIZOLINI'
	  )
 ORDER BY Candidato.NOME_CANDIDATO, Bens.ANO_ELEICAO DESC


SELECT TOP 1000  
		Candidato.NOME_CANDIDATO, 
		Bens.ANO_ELEICAO, 
		Candidato.DESCRICAO_ELEICAO,  
		'R$ ' + CAST(
						SUM(
								CAST(VALOR_BEM AS NUMERIC(14,2))
							)
					  AS VARCHAR(20)) AS Total

  FROM ImportacaoCandidato					AS Candidato  	WITH(NOLOCK)
  JOIN [dbo].[ImportacaoBensCandidato]		AS Bens  		WITH(NOLOCK)
    ON Candidato.SEQUENCIAL_CANDIDATO = Bens.SQ_CANDIDATO
   AND Candidato.ANO_ELEICAO = Bens.ANO_ELEICAO
 WHERE Candidato.SIGLA_UF = 'SP'
   AND Candidato.DESCRICAO_UE = 'VOTORANTIM'
   AND (	
			 Candidato.NOME_CANDIDATO = 'FERNANDO DE OLIVEIRA SOUZA'
		  OR Candidato.NOME_CANDIDATO = 'JAIR CASSOLA'
		  OR Candidato.NOME_CANDIDATO LIKE 'ERINALDO ALVES DA SILVA'
		  OR Candidato.NOME_CANDIDATO LIKE 'CARLOS ALBERTO LEITE'
		  OR Candidato.NOME_CANDIDATO LIKE 'RODRIGO PINTO CHIZOLINI'
	  )
 GROUP BY Bens.ANO_ELEICAO, Candidato.NOME_CANDIDATO, Candidato.DESCRICAO_ELEICAO
 ORDER BY Candidato.NOME_CANDIDATO, Bens.ANO_ELEICAO DESC